### PR TITLE
k8s: update docker and k8s inline with developer guidelines

### PR DESCRIPTION
**Pull request by piersharding**
Refactor the Docker and Kubernetes support to align with standards/guidelines http://developer.skatelescope.org/en/latest/development/containerisation-standards.html and http://developer.skatelescope.org/en/latest/development/orchestration-guidelines.html

### CODE REVIEW

**Comment by piersharding** [comment]
HI @timcornwell - could you please have a look at this merge request.  It is a refactor of the Docker build process and the Kubernetes Helm Chart to align with System Teams guidelines that I've been working on.  There is no rush for it.

Thanks,
Piers.

**Comment by timcornwell** [comment]
Fails because of Dask problem. Will work on that.

**Comment by timcornwell** [comment]
Accepted

**Comment by piersharding** [comment]
Hey - thanks for sorting out the problems.

**Pull request merged**
