### PR TITLE
UVFITS Reader

### PR DESCRIPTION
**Pull request by cnwangfeng**
Hi Tim, 

Thank you for the consideration to include UVFITS support in ARL. 

1. base.py:  We add two functions such as create_blockvisibility_from_uvfits and create_visibility_from_uvfits. The codes have been tested strictly. Frankly speaking, the current function can't support all variations of UVFITS because it's too complex. The arguments of the functions are similar to the functions of MS file. 

2. test_visibility_uvfits: Testing codes 

3. ASKAP_example.fits :  I finally upload the testing data because I found test program can't pass.
Cheers, 

Feng

### CODE REVIEW

**Comment by cnwangfeng** [comment]
Sry for re-committing the one file.

**Comment by timcornwell** [comment]
That's fine. Thanks for submitting the PR.

**Comment by cnwangfeng** [comment]
Yes. I found the errors. Shall I commit again? I am using PyCharm and Visual Studio Code alternatively.

Regards,

Feng

**Comment by timcornwell** [comment]
No I fixed them.

**Comment by cnwangfeng** [comment]
Thanks. Have a nice weekend.

BTW, is it possible to add “**/.DS_Store” in .gitignore of master at your convenience?

Cheers,

Feng

**Comment by timcornwell** [comment]
Yes, I will do.

**Comment by timcornwell** [comment]
Actually I have a global ~/.gitignore_global containing:
*~
.DS_Store
That would be better, I think.

**Pull request merged**
