### PR TITLE
Build and test tweaks

### PR DESCRIPTION
**Pull request by piersharding**
HI Tim -

These are a bunch of fixes that I have for working with Python 3.7 and also some Makefile help.

Thanks,
Piers.

### CODE REVIEW

**Comment by piersharding** [comment]
Sorry - I would investigate the Jenkins failure above, but I have no access to the logs.

**Comment by timcornwell** [comment]
Hi Piers,

Sorry about not getting to the PR. I was offline for a couple of days. The PR58 build failed because of an intermittent Dask error of a notebook. I’ve relaunched the build and will try to hunt down the cause of the Dask error.

I’ll watch for the next build.

Cheers,
Tim

**Comment by timcornwell** [comment]
Relaunched the build and it passed this time.

**Comment by piersharding** [comment]
Cool - thanks

**Pull request merged**
